web:
  image: node:4.2-wheezy
  net: "host"
  volumes:
   - .:/opt/app/src
  env_file:
    - ./.env
  container_name: todo
links:
- mongo
- redis
mongo:
 image: mongo:3.2.1
  ports:
    - "27017:27017"
  container_name: mongo
redis:
  image: redis:3.0.6-alpine
  ports:
    - "6379:6379"
  container_name: redis
